### ISSUE TITLE
why there is no 0.5* in the equation of the derivative of sate(t)  ?

### ISSUE THREAD

**Issue by tinymindxx** [nicodjimenez/lstm#33]
thanks for your great work on this blog, it's the clearest  and simplest blog on lstm i have read.
in your blog,  derivative of s(t) is get by this equation,
![image](https://user-images.githubusercontent.com/5286725/36954928-1eb2c4b4-2060-11e8-85ac-5aa3079e977d.png)
i wonder why the left of this equation is equal to the right. 
in my opinion, left = 0.5*right. and why we need the **top_diff_s** if we could calculate 
![image](https://user-images.githubusercontent.com/5286725/36970008-08f0c53a-20a2-11e8-8082-67b81d9cbc5d.png) directly.
![image](https://user-images.githubusercontent.com/5286725/36970071-407979de-20a2-11e8-8686-6b07c3fa4e15.png)

I am new to nn and lstm, your blog is the best and clearest blog about implement and derivation of lstm, thanks for your great work.

**Comment by nicodjimenez** [comment]
Glad you find the post useful.  

The chain rule of calculus says that in order to calculate the left derivative, you need to take into account all intermediate variables that are affected by changes in s_i which themselves will affect L(t).  In this example the only intermediate variables are h_i(t) and h_i(t+1).

Why do you think that left = 0.5*right?

**Comment by nicodjimenez** [comment]
The section called "Higher dimensions" is relevant here: https://en.wikipedia.org/wiki/Chain_rule

**Comment by tinymindxx** [comment]
@nicodjimenez  hi, thanks for your reply, it's really very very kind of you.

I think in the equation  bellow， 
![image](https://user-images.githubusercontent.com/5286725/37516172-3aef2438-2948-11e8-9e68-3f6ce99b7c9e.png)
left = 0.5*right is because ：

![image](https://user-images.githubusercontent.com/5286725/37518806-bc4c6dd4-2951-11e8-89a5-d15afd21c441.png)
so we can get:
![image](https://user-images.githubusercontent.com/5286725/37518997-91cb99bc-2952-11e8-8b82-5eabdef648b9.png)

in my opinion, the derivative is :
![image](https://user-images.githubusercontent.com/5286725/37576432-55f0bea6-2b67-11e8-8467-6d83fb15a24c.png)

once we can get **top_diff_h** , we can get **dsi(t)**

and in your code,
![image](https://user-images.githubusercontent.com/5286725/37519168-146e1cb4-2953-11e8-9f4b-8fe5adc6d1dd.png)
if we change        
```python
ds = self.state.o * top_diff_h + top_diff_s
```
to 
```
ds = self.state.o * top_diff_h 
```
it's more likely to get a lower loss in my test.

I don't know where is the wrong point, hope you can get more tips.

thanks for your reply again!

**Comment by nicodjimenez** [comment]
This is the same point as the one made in https://github.com/nicodjimenez/lstm/pull/49.  Please move discussion there.  

Also, I don't follow your math:

![image](https://user-images.githubusercontent.com/3152743/126708213-debdb343-3032-4646-90f8-86796e13096b.png)
